name: Release
on:
  release:
    types: [created]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test:contracts
          npm run test:package
      - name: Archive contract ABI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bridge-abi-artifacts
          path: artifacts
      - name: Archive package dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bridge-dist-artifacts
          path: dist
  release:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: bridge-abi-artifacts
          path: artifacts
      - uses: actions/download-artifact@v2
        with:
          name: bridge-dist-artifacts
          path: dist
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@trustline"
      # Publish to GitHub Packages
      - run: |
          npm install
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}